module.exports={
    entry:{
        app:'app.js'
    },
    output:{
        filename:'[name].[hash:8].js'
    },
    module:{
        rules:[{
            test:/\.js$/,
            use:{
                loader:'babel-loader',
                options:{
                    presets:['env']
                }
            },
            exclude:'/node_modules/'
        }]
    }
}